heat_template_version: 2015-04-30

description: Deploy a LTM disaggregated AFM/CGNAT F5 cluster


parameters:
  use_config_drive:
    type: boolean
    label: Use Config Drive
    description: Use config drive to provider meta and user data.
    default: false
  f5_ve_os_ssh_key:
    type: string
    label: F5 FW Root SSH Key Name
    description: Name of key-pair to be installed on the FW instances.
    constraints:
      - custom_constraint: nova.keypair
  f5_ve_os_ssh_value:
    type: string
    label: F5 FW Root SSH Key Value
    description: To be added to authorized_keys of VE.
  admin_password:
    type: string
    label: F5 VE Admin User Password
    description: Password used to perform image import services
    hidden: true
  root_password:
    type: string
    label: F5 VE Root User Password
    description: Password used to perform image import services
    hidden: true
  bigiq_license_pool_host:
    type: string
    label: BIG-IQ used for pool licensing
    description: BIG-IP will request a license from a pool license in this BIG-IQ. Specify DNS name or IP address."
  bigiq_license_pool_name:
    type: string
    label: Pool license name
    description: The pool license name as it appears in BIG-IQ
  bigiq_license_pool_user:
    type: string
    label: BIG-IQ user to retrieve the license from
    default: admin
  bigiq_license_pool_password:
    type: string
    label: BIG-IQ password of the user used to retrieve the license from
    default: admin
  ltm_ve_amount:
    type: number
    label: Number of VE instances
    description: Number of VE instances to deploy
  ltm_ve_name_prefix:
    type: string
    label: VE Naming prefix (ex LTM,CGN)
    description: Prefix that helps to identify the main purpose of the deployed VEs
    default: LTM-VE-
  ltm_ve_image:
    type: string
    label: F5 VE Image
    description: The image to be used on the compute instance.
    constraints:
      - custom_constraint: glance.image
  ltm_ve_flavor:
    type: string
    label: F5 VE Flavor
    description: Type of instance (flavor) to be used for the VE.
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor
  mgmt_network:
    type: string
    label: VE Management Network
    description: Management Interface Network.
    default: test
    constraints:
      - custom_constraint: neutron.network
  ex_mgmt_network:
    type: string
    label: External VE Management Network
    description: External Management Interface Network for floating IP.
    default: mgmt
    constraints:
      - custom_constraint: neutron.network
  ltm_network_1:
    type: string
    label: VE Network for the 1.1 Interface
    description: TMM 1.1 network.
    default: test
    constraints:
      - custom_constraint: neutron.network
  ltm_network_1_name:
    type: string
    label: VE Network Name for the 1.1 Interface
    description: TMM 1.1 network name.
    default: network-1.1
  ltm_network_2:
    type: string
    label: VE Network for the 1.2 Interface
    description: TMM 1.2 network.
    default: test
    constraints:
      - custom_constraint: neutron.network
  ltm_network_2_name:
    type: string
    label: VE Network Name for the 1.2 Interface
    description: TMM 1.2 network name.
    default: network-1.2
  default_gateway:
    type: string
    label: Default Gateway IP
    default: None
    description: Upstream Gateway IP Address for VE instances
  afm_ve_amount:
    type: number
    label: Number of VE instances
    description: Number of VE instances to deploy
  afm_ve_name_prefix:
    type: string
    label: VE Naming prefix (ex LTM,CGN)
    description: Prefix that helps to identify the main purpose of the deployed VEs
    default: AFM-VE-
  afm_ve_image:
    type: string
    label: F5 VE Image
    description: The image to be used on the compute instance.
    constraints:
      - custom_constraint: glance.image
  afm_ve_flavor:
    type: string
    label: F5 VE Flavor
    description: Type of instance (flavor) to be used for the VE.
    default: m1.medium
    constraints:
      - custom_constraint: nova.flavor
  afm_network_1:
    type: string
    label: VE Network for the 1.1 Interface
    description: TMM 1.1 network.
    default: test
    constraints:
      - custom_constraint: neutron.network
  afm_network_1_name:
    type: string
    label: VE Network Name for the 1.1 Interface
    description: TMM 1.1 network name.
    default: network-1.1
  afm_network_2:
    type: string
    label: VE Network for the 1.2 Interface
    description: TMM 1.2 network.
    default: test
    constraints:
      - custom_constraint: neutron.network
  afm_network_2_name:
    type: string
    label: VE Network Name for the 1.2 Interface
    description: TMM 1.2 network name.
    default: network-1.2
  afm_network_3:
    type: string
    label: VE Network for the 1.3 Interface
    description: TMM 1.3 network.
    constraints:
      - custom_constraint: neutron.network
  afm_network_3_name:
    type: string
    label: VE Network Name for the 1.3 Interface
    description: TMM 1.3 network name.
    default: network-1.3



parameter_groups:
- parameters:
  - use_config_drive
- parameters:
  - f5_ve_os_ssh_key
  - f5_ve_os_ssh_value
  - admin_password
  - root_password
- parameters:
  - bigiq_license_pool_host
  - bigiq_license_pool_name
  - bigiq_license_pool_user
  - bigiq_license_pool_password
- parameters:
  - mgmt_network
  - ex_mgmt_network
- parameters:
  - ltm_ve_amount
  - ltm_ve_name_prefix
  - ltm_ve_image
  - ltm_ve_flavor
  - ltm_network_1
  - ltm_network_1_name
  - ltm_network_2
  - ltm_network_2_name
  - afm_ve_amount
  - afm_ve_name_prefix
  - afm_ve_image
  - afm_ve_flavor
  - afm_network_1
  - afm_network_1_name
  - afm_network_2
  - afm_network_2_name
  - afm_network_3
  - afm_network_3_name
  - default_gateway

resources:
  M_afm_devices:
    type: DeployN_VE_4NIC_BIGIQ.yaml
    properties:
      ve_amount: { get_param: afm_ve_amount }
      ve_name_prefix: { get_param: afm_ve_name_prefix }
      ve_image: { get_param: afm_ve_image }
      ve_flavor: { get_param: afm_ve_flavor }
      f5_ve_os_ssh_key: { get_param: f5_ve_os_ssh_key }
      f5_ve_os_ssh_value: { get_param: f5_ve_os_ssh_value }
      use_config_drive: { get_param: use_config_drive }
      admin_password: { get_param: admin_password }
      root_password: { get_param: root_password }
      bigiq_license_pool_host: { get_param: bigiq_license_pool_host }
      bigiq_license_pool_name: { get_param: bigiq_license_pool_name }
      bigiq_license_pool_user: { get_param: bigiq_license_pool_user }
      bigiq_license_pool_password: { get_param: bigiq_license_pool_password }
      mgmt_network: { get_param: mgmt_network }
      ex_mgmt_network: { get_param: ex_mgmt_network }
      network_1: { get_param: afm_network_1 }
      network_2: { get_param: afm_network_2 }
      network_3: { get_param: afm_network_3 }
      network_1_name: { get_param: afm_network_1_name }
      network_2_name: { get_param: afm_network_2_name }
      network_3_name: { get_param: afm_network_3_name }

  N_ltm_devices:
    type: DeployN_VE_3NIC_BIGIQ.yaml
    depends_on: M_afm_devices
    properties:
      ve_amount: { get_param: ltm_ve_amount }
      ve_name_prefix: { get_param: ltm_ve_name_prefix }
      ve_image: { get_param: ltm_ve_image }
      ve_flavor: { get_param: ltm_ve_flavor }
      f5_ve_os_ssh_key: { get_param: f5_ve_os_ssh_key }
      f5_ve_os_ssh_value: { get_param: f5_ve_os_ssh_value }
      use_config_drive: { get_param: use_config_drive }
      admin_password: { get_param: admin_password }
      root_password: { get_param: root_password }
      bigiq_license_pool_host: { get_param: bigiq_license_pool_host }
      bigiq_license_pool_name: { get_param: bigiq_license_pool_name }
      bigiq_license_pool_user: { get_param: bigiq_license_pool_user }
      bigiq_license_pool_password: { get_param: bigiq_license_pool_password }
      mgmt_network: { get_param: mgmt_network }
      ex_mgmt_network: { get_param: ex_mgmt_network }
      network_1: { get_param: ltm_network_1 }
      network_2: { get_param: ltm_network_2 }
      network_1_name: { get_param: ltm_network_1_name }
      network_2_name: { get_param: ltm_network_2_name }


outputs:
  ltm_mgmt_ips:
    description: IPs for mgmt of the N LTM devices
    value: {get_attr: [N_ltm_devices, mgmt_floating_ips] }
  afm_mgmt_ips:
    description: IPs for mgmt of the M AFM devices
    value: {get_attr: [M_afm_devices, mgmt_floating_ips] }
  ltm_afm_pool_members:
    description: Self IPs of all the AFMs in the mobile side subnet in pool member format selfip:0
    value: { get_attr: [ M_afm_devices, mobile_side_pool_members] }
