parameters:
  use_config_drive: true
  f5_ve_os_ssh_key: DemoKey
  f5_ve_os_ssh_value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmGHnFFIbr/9vh9D324J7fvF4PXcCQY8KmkGv/yhdOD1lyBhf0yPNqlgFo40+tJkZbDoBa7UCyQW3eGylVgkcoBbPqeDxmeHm2QrWWD4x8AB3mkC4O890X1KCTI/1S8ep6pVZDieBAkY/6vnoEOyvPfO8cBr/qNxlcgXRyTEl1zMXzOzJn3nqnjruk+OWhHUYOQOv8bHHhRD8ElOkfFqbEj52VwoIwLRw1FuneQIz3A/ekIYY9YY6X+4zFFqXmTL6CyURy2fa8WfPgmgqBgo3WdfbgndPjIHhN/vCCggHEJdatUjtAD25hkSVM7t4IzZ5P5PDAgmygPpb8oQ7Xkh39 Generated-by-Nova"
  admin_password: admin
  root_password: default

  bigiq_license_pool_host: 10.103.14.84
  bigiq_license_pool_user: admin
  bigiq_license_pool_password: admin
  bigiq_license_pool_name: 25_best_pool_recyclable_30_day
  mgmt_network: int_mgmt
  ex_mgmt_network: mgmt

  ve_name: LTM-Test-VE
  ve_image:  BIGIP-13.0.0.2.0.1671.HF2.LTM_1SLOT
  ve_flavor: F5VE10G_LTM_1SLOT_8GB_NUMA.performance

  network_1: provider-vlan3009
  network_1_name: provider-vlan3009
  network_2: ltm_pem_afm_lan
  network_2_name: ltm_pem_afm_lan
